"""add_clock_state

Revision ID: 4048678bf782
Revises: a1b2c3d4e5f6
Create Date: 2026-02-06 14:46:07.670736

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4048678bf782'
down_revision = 'a1b2c3d4e5f6'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches', sa.Column('last_start_ts', sa.DateTime(timezone=True), nullable=True))
    op.add_column('matches', sa.Column('accumulated_time_ms', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('matches', sa.Column('is_running', sa.Boolean(), nullable=False, server_default='false'))
    
    # Drop defaults if you don't want them persisted (optional, keeping them is safer)
    op.alter_column('matches', 'accumulated_time_ms', server_default=None)
    op.alter_column('matches', 'is_running', server_default=None)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('matches', 'is_running')
    op.drop_column('matches', 'accumulated_time_ms')
    op.drop_column('matches', 'last_start_ts')
    # ### end Alembic commands ###
