"""add_score_columns

Revision ID: 62a7da274c8d
Revises: 4048678bf782
Create Date: 2026-02-06 15:33:01.563088

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62a7da274c8d'
down_revision = '4048678bf782'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches', sa.Column('score_local', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('matches', sa.Column('score_visitor', sa.Integer(), nullable=False, server_default='0'))
    
    # Remove default after creation if desired (cleaner schema), or keep it. Keeping is fine.
    op.alter_column('matches', 'score_local', server_default=None)
    op.alter_column('matches', 'score_visitor', server_default=None)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('matches', 'score_visitor')
    op.drop_column('matches', 'score_local')
    # ### end Alembic commands ###
