"""create_match_events_table

Revision ID: 65400620b1ea
Revises: 97eb28a5a4d0
Create Date: 2026-02-07 09:16:50.276193

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65400620b1ea'
down_revision = '97eb28a5a4d0'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
