"""create_match_events_table

Revision ID: 65400620b1ea
Revises: 97eb28a5a4d0
Create Date: 2026-02-07 09:16:50.276193

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65400620b1ea'
down_revision = '62a7da274c8d'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('match_events',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('match_id', sa.UUID(), nullable=False),
        sa.Column('event_type', sa.Enum('GOAL', 'YELLOW_CARD', 'RED_CARD', 'TWO_MIN', 'TIMEOUT', name='matcheventtype'), nullable=False),
        sa.Column('team_side', sa.Enum('LOCAL', 'VISITOR', name='teamside'), nullable=False),
        sa.Column('minute', sa.Integer(), nullable=False),
        sa.Column('player_number', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('match_events')
    # Dropping enums might be needed if not autogenerated cleanup? 
    # Usually alembic doesn't drop types automatically on some versions but let's stick to table drop.
    sa.Enum(name='matcheventtype').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='teamside').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
