"""fix_match_event_fk_type

Revision ID: 8b1ae317e45c
Revises: 65400620b1ea
Create Date: 2026-02-07 09:18:19.729568

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b1ae317e45c'
down_revision = '65400620b1ea'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
