"""initial_migration

Revision ID: 97eb28a5a4d0
Revises: 62a7da274c8d
Create Date: 2026-02-07 09:05:20.078719

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97eb28a5a4d0'
down_revision = '62a7da274c8d'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('matches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('home_team', sa.String(), nullable=False),
    sa.Column('visitor_team', sa.String(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_half', sa.Integer(), nullable=False),
    sa.Column('current_half', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_start_ts', sa.DateTime(timezone=True), nullable=True),
    sa.Column('accumulated_time_ms', sa.Integer(), nullable=False),
    sa.Column('is_running', sa.Boolean(), nullable=False),
    sa.Column('score_local', sa.Integer(), nullable=False),
    sa.Column('score_visitor', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('matches')
    # ### end Alembic commands ###
